default: &default
  adapter: postgresql
  pool: 5
  user: postgres
  password: 123456
  host: localhost

development:
  <<: *default
  database: ewl_dev

test:
  <<: *default
  database: ewl_test


production:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  pool: 25
  port: 5432
  username: postgres
  password: 123456
  database: ewl_dev
